# Enable save-exact
savePrefix: ''

# Allow install scripts
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - es5-ext
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract
  - sharp
